uploadSizeLimit=5
uploadUserSizeLimit=1000
maxFileNameLength = 100
maxAttachmentCount = 1000
maxImageWidth = 30000
maxImageHeight = 30000
maxNotificationCapacity = 100
maxNotificationAgeDays = 30
appMode = DEV


