version: "3.9"
services:
  db:
    container_name: WikiApiDB
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: wikiapi
    ports:
      - "5432:5432"

