CREATE TABLE user_profiles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    description VARCHAR(255),
    nsfw BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    name    VARCHAR(255) UNIQUE NOT NULL ,
    email    VARCHAR(255) UNIQUE NOT NULL ,
    role    VARCHAR(255) NOT NULL ,
    hashed_password    VARCHAR(255),
    created_at TIMESTAMP with time zone NOT NULL,
    profile_id BIGINT NOT NULL,
    oauth_id BIGINT,
    auth_provider VARCHAR(8) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_profile_id FOREIGN KEY (profile_id) REFERENCES user_profiles (id) ON DELETE CASCADE,
    CONSTRAINT uc_oauth_id_auth_provider UNIQUE (oauth_id, auth_provider)
);

CREATE TABLE files
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    created_at TIMESTAMP with time zone NOT NULL,
    name VARCHAR(255),
    caption VARCHAR(255),
    storage_id VARCHAR(255),
    author_id BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(255) NOT NULL,

    CONSTRAINT pk_files PRIMARY KEY (id),
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT uc_storage_id UNIQUE (storage_id)
);


CREATE TABLE user_profile_pictures
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    file_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,

    CONSTRAINT pk_profile_pictures PRIMARY KEY (id),
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_id FOREIGN KEY (profile_id) REFERENCES user_profiles (id) ON DELETE CASCADE,
    CONSTRAINT uc_profile_pictures UNIQUE (file_id, profile_id)
);

create TABLE follows
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP with time zone                NOT NULL,
    follower_id      BIGINT,
    followee_id      BIGINT,
    notifications_enabled   BOOLEAN DEFAULT FALSE NOT NULL,
    muted                 BOOLEAN DEFAULT FALSE NOT NULL,

    CONSTRAINT pk_follows PRIMARY KEY (id),
    CONSTRAINT fk_follower_id FOREIGN KEY (follower_id) REFERENCES users (id),
    CONSTRAINT fk_followee_id FOREIGN KEY (followee_id) REFERENCES users (id),
    CONSTRAINT uc_follows UNIQUE (follower_id, followee_id)
);


CREATE TABLE content
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id BIGINT,
    created_at TIMESTAMP with time zone NOT NULL,
    updated_at TIMESTAMP with time zone NOT NULL,
    nsfw BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_content PRIMARY KEY (id),
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id)
);


CREATE TABLE timelines
(
    id BIGINT NOT NULL,
    name    VARCHAR(255) NOT NULL ,
    description VARCHAR(255) NOT NULL,

    CONSTRAINT pk_timelines PRIMARY KEY (id),
    CONSTRAINT uc_timelines_name UNIQUE (name),
    CONSTRAINT fk_id FOREIGN KEY (id) REFERENCES content (id) ON DELETE CASCADE
);


CREATE TABLE articles
(
    id BIGINT NOT NULL,
    title    VARCHAR(128),
    body    TEXT NOT NULL,

    CONSTRAINT pk_articles PRIMARY KEY (id),
    CONSTRAINT fk_id FOREIGN KEY (id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    name    VARCHAR(63) NOT NULL ,
    description VARCHAR(255),
    nsfw BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uc_name UNIQUE (name)
);

CREATE INDEX tag_names ON tags (name);

CREATE TABLE tags_to_content
(
    tag_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,

    CONSTRAINT pk_tags_to_content PRIMARY KEY (tag_id, content_id),
    CONSTRAINT fk_tag_id FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT fk_content_id FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE,
    CONSTRAINT uc_tags_to_content UNIQUE (tag_id, content_id)
);


-- Ensure that if article has a timeline Id, the index must NOT be null.
-- Also articles to timelines is many:1.
CREATE TABLE timeline_entries
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    timeline_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    timeline_index BIGINT NOT NULL,

    CONSTRAINT pk_timeline_entries PRIMARY KEY (id),
    CONSTRAINT fk_timeline_id FOREIGN KEY (timeline_id) REFERENCES timelines (id) ON DELETE CASCADE,
    CONSTRAINT fk_article_id FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT uc_timeline_id_all UNIQUE (timeline_id, timeline_index, article_id),
    CONSTRAINT uc_timeline_id_article_id UNIQUE (timeline_id, article_id),
    CONSTRAINT uc_timeline_index UNIQUE (timeline_id, timeline_index) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE social_media_links
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    platform VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    profile_id BIGINT NOT NULL,

    CONSTRAINT pk_social_media_links PRIMARY KEY (id),
    CONSTRAINT fk_profile_id FOREIGN KEY (profile_id) REFERENCES user_profiles (id) ON DELETE CASCADE
);

CREATE TABLE files_to_articles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    file_id BIGINT,
    article_id BIGINT,
    index BIGINT NOT NULL,

    CONSTRAINT pk_files_to_articles PRIMARY KEY (id),
    CONSTRAINT fk_article_id FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT uc_files_to_articles UNIQUE (article_id, index) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE characters
(
    id BIGINT NOT NULL,
    name VARCHAR(255),
    body TEXT NOT NULL,

    CONSTRAINT pk_characters PRIMARY KEY (id),
    CONSTRAINT fk_id FOREIGN KEY (id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE TABLE articles_to_characters
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    article_id BIGINT NOT NULL,
    character_id BIGINT NOT NULL,

    CONSTRAINT pk_articles_to_characters PRIMARY KEY (id),
    CONSTRAINT uc_articles_to_characters UNIQUE (article_id, character_id),
    CONSTRAINT fk_article_id FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_character_id FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE
);

CREATE TABLE files_to_characters
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    file_id BIGINT,
    character_id BIGINT,
    index BIGINT NOT NULL,

    CONSTRAINT pk_files_to_characters PRIMARY KEY (id),
    CONSTRAINT fk_character_id FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT uc_files_to_characters UNIQUE (file_id, character_id, index)
);

CREATE TABLE files_to_character_profiles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    file_id BIGINT,
    character_id BIGINT,
    index BIGINT NOT NULL,

    CONSTRAINT pk_files_to_character_profiles PRIMARY KEY (id),
    CONSTRAINT fk_character_id FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_id FOREIGN KEY (file_id) REFERENCES files (id) ON DELETE CASCADE,
    CONSTRAINT uc_files_to_character_profiles UNIQUE (file_id, character_id, index)
);

CREATE TABLE comments
(
    id BIGINT NOT NULL,
    body    TEXT NOT NULL,

    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_id FOREIGN KEY (id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE TABLE comments_to_content
(
    comment_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,

    CONSTRAINT pk_comments_to_content PRIMARY KEY (comment_id, content_id),
    CONSTRAINT fk_comment_id FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE,
    CONSTRAINT fk_content_id FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE,
    CONSTRAINT uc_comments_to_content UNIQUE (comment_id, content_id)
);

CREATE TABLE comment_replies
(
    reply_to_id BIGINT NOT NULL,
    reply_id BIGINT NOT NULL,

    CONSTRAINT pk_comment_replies PRIMARY KEY (reply_id, reply_to_id),
    CONSTRAINT fk_reply_to_id FOREIGN KEY (reply_to_id) REFERENCES comments (id),
    CONSTRAINT fk_reply_id FOREIGN KEY (reply_id) REFERENCES comments (id),
    CONSTRAINT uc_comment_replies UNIQUE (reply_id, reply_to_id)
);

CREATE TABLE likes
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    author_id BIGINT NOT NULL,
    emoji TEXT,
    owning_content_id BIGINT NOT NULL,

    CONSTRAINT pk_likes PRIMARY KEY (id),
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_owning_content_id FOREIGN KEY (owning_content_id) REFERENCES content ON DELETE CASCADE
);

CREATE TABLE traits
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32) NOT NULL,
    val VARCHAR(64) NOT NULL,
    character_id BIGINT NOT NULL,

    CONSTRAINT pk_traits PRIMARY KEY (id),
    CONSTRAINT fk_character_id FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    CONSTRAINT uc_trait_name_to_characters UNIQUE (name, character_id)
);

-- Notifications have a subject (user) that does notif type (enum) to an target (content).
-- The recipient is the user that receives the notification.
CREATE TABLE notifications
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    subject_id BIGINT,
    target_content_id BIGINT,
    notification_type VARCHAR(255) NOT NULL,
    message VARCHAR(255),
    created_at TIMESTAMP with time zone NOT NULL,

    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT fk_subject_id FOREIGN KEY (subject_id) REFERENCES users (id),
    CONSTRAINT fk_target_content_id FOREIGN KEY (target_content_id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE TABLE notifications_to_recipients
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_notifications_to_users PRIMARY KEY (id),
    CONSTRAINT fk_notification_id FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uc_notifications_to_users UNIQUE (notification_id, user_id)
);

CREATE TABLE reports
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    author_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    created_at TIMESTAMP with time zone NOT NULL,
    reported_content_id BIGINT NOT NULL,
    resolver_id BIGINT,

    CONSTRAINT pk_reports PRIMARY KEY (id),
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reported_content_id FOREIGN KEY (reported_content_id) REFERENCES content (id) ON DELETE CASCADE,
    CONSTRAINT fk_resolver_id FOREIGN KEY (resolver_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE announcements
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP with time zone NOT NULL,
    updated_at TIMESTAMP with time zone NOT NULL,

    CONSTRAINT pk_announcements PRIMARY KEY (id)
);




