CREATE TABLE users
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    name    VARCHAR(255) UNIQUE NOT NULL ,
    email    VARCHAR(255) UNIQUE NOT NULL ,
    role    VARCHAR(255) NOT NULL ,
    hashed_password    VARCHAR(255),
    createdAt TIMESTAMP with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)

);

CREATE TABLE articles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    title    VARCHAR(255),
    body    TEXT,
    createdAt TIMESTAMP with time zone NOT NULL,
    CONSTRAINT pk_articles PRIMARY KEY (id)
);