import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./Footer";
import { Toaster } from "@/components/ui/toaster";
import Alert from "@/components/CustomUi/Alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Kronica",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="lg:w-[70vw] mx-auto">
                <Navbar />

                <div className="min-h-[60px] "></div>

                {/* <Alert message="ds" /> */}
                <main className="flex min-h-screen flex-col m-3 lg:w-[70vw] mx-auto p-2">
                    {children}
                </main>
                <Footer />
                <Toaster />
            </body>
        </html>
    );
}
